name: PR Labeler
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
